name       = "poly-glot-auth"
main       = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "AUTH_KV"
id      = "4686b5dd158944e5856f7a402c6c6d2f"

[vars]
BASE_URL = "https://poly-glot.ai"

[[routes]]
pattern = "poly-glot.ai/api/auth/*"
zone_name = "poly-glot.ai"
